### PR TITLE
Swiftify interface

### PR DESCRIPTION
**Pull request by mstarke**
This is an attempt to remove the need of a dedicated Swift source file to make KissXML pure Obj-C again. Please consider this PR with caution as I am no Swift expert. The tests for iOS run fine, macOS test did crash in NSXml under Xcode 9.2 and macOS 10.12 for unknown reasons.

### CODE REVIEW

**Comment by chrisballinger** [comment]
Oh awesome! I tried to do this myself in the past and got stuck due to not know about about `@compatibility_alias`.

Can you verify that these changes don't break the `XMPPFramework/Swift` podspec here https://github.com/robbiehanson/XMPPFramework on macOS and iOS?

```ruby
# XMPPFramework with Swift extensions
pod 'XMPPFramework/Swift', :git => 'https://github.com/robbiehanson/XMPPFramework.git', :branch => 'master'
pod 'KissXML', :git => 'https://github.com/MacPass/KissXML.git', :branch => 'swiftless'
```

**Comment by mstarke** [comment]
I just build XMPPFramework with the proposed KissXML version and the build succeeds. I have no idea if any runtime stuff is broken though.

**Comment by chrisballinger** [comment]
Both macOS and iOS?

**Comment by mstarke** [comment]
Yup. Both builds succeeded. I didn't see any unit test, are there any to ensure the functionality is actually correct?

**Comment by chrisballinger** [comment]
There are unit tests in the `XMPPFramework/Xcode` directory, check the `.travis.yml` file to see how to run them all from the command line

**Pull request merged**
